SCREEN 3

PRINT "BASLOAD IS BASIC WITHOUT LINE NUMBERS"
PRINT "IF THIS IS BETTER OR NOT, IS UP TO YOU"
PRINT "YOU USE LABELS INSTEAD OF LINE NUMBERS"
PRINT "FOR YOUR GOTO OR GOSUB OPERATIONS."

GOSUB TERRA
GOSUB EARTH
GOSUB MOON

END


TERRA:
PRINT "LABEL TERRA REACHED."
RETURN

EARTH:
PRINT "LABEL EARTH REACHED."
RETURN

MOON:
PRINT "LABEL MOON REACHED."
RETURN
