1 REM     =========!=========!=========!=========!
2 SCREEN 3 : REM SET 40 CHAR SCREEN JUST FOR FUN
10 PRINT "  WELCOME TO THE COMMANDER X16 (CX16)"
20 PRINT "  COLLECTION OF INFORMATION SNIPPETS."
30 PRINT "  AND (MAYBE) USEFUL EXAMPLES."
